webhook:
  enabled: true

gitRepos:
  code: https://github.com/marbindrakon/quarkus-esp-wrangler
  fw: https://github.com/marbindrakon/esp-mqtt-sensor

imageRegistries:
  espWrangler: quay.signal9.gg/home-automation/quarkus-esp-wrangler
  pioBuilder:  quay.signal9.gg/home-automation/platformio-builder
  firmwareServer: quay.signal9.gg/home-automation/fw-download-httpd

vaultSecrets:
  enabled: true
  imageRegistry: tekton-demo-quay
  firmwareSigning: tekton-test-key
