apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: platformio-build
spec:
  steps:
    - image: {{ .Values.imageRegistries.pioBuilder }}:latest
      name: 'platformio-build'
      resources: {}
      script: >
        #!/bin/bash

        set -xe

        cd /code

        git config --global --add safe.directory /code
        
        git fetch --unshallow

        VERSION=$(git describe --long --dirty)

        echo "Building FW $VERSION"

        pio lib install

        pio run

        mkdir -p /fw-files/release

        mkdir -p /fw-files/debug

        ./tools/signing.py -m sign -b .pio/build/release/firmware.bin -s
        /signing/privkey.pem -o /fw-files/release/$VERSION-release.bin

        ./tools/signing.py -m sign -b .pio/build/debug/firmware.bin -s
        /signing/privkey.pem -o /fw-files/debug/$VERSION-debug.bin
  workspaces:
    - mountPath: /code
      name: fw-code
    - mountPath: /fw-files
      name: fw-files
    - mountPath: /signing
      name: signing
      readOnly: true
