{{- if .Values.webhook.enabled -}}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: code-template
spec:
  params:
    - description: The git repository url
      name: git-repo-url
    - default: master
      description: The git revision
      name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: code-build-$(uid)
      spec:
        params:
          - name: code_repo
            value: '$(params.git-repo-url)'
          - name: git_rev
            value: '$(params.git-revision)'
        pipelineRef:
          name: esp-wrangler-git-commit
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: code
            volumeClaimTemplate:
              metadata:
                creationTimestamp: null
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                volumeMode: Filesystem
              status: {}
          - name: registry-secret
            secret:
              secretName: image-registry-secret
          - emptyDir: {}
            name: maven-settings
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: code-template
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: github-push
          kind: ClusterTriggerBinding
      template:
        ref: code-template
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: esp-code-github
spec:
  to:
    kind: Service
    name: el-code-template
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{ end }}
