{{- if .Values.vaultSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fw-signing-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: fw-signing-key
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.vaultSecrets.firmwareSigning }}
{{ end }}
