{{- if .Values.vaultSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: image-registry-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: image-registry-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.vaultSecrets.imageRegistry }}
{{ end }}
